name: "Skysong_Items"
main: com.skysongdev.skysongitems.Main
version: ${version}
authors: [Ghiojo]
api-version: "1.20"
commands:
  getlore:
    description: Description.
    usage: /getlore
    permission: skysongitems.getlore
    permission-message: "You do not have permission to use this command!"
  physdesc:
    description: "add or set a the Physical description of an item (first paragraph)"
    usage: "/physdesc add [LORE]\n/physdesc set [LORE]\n/physdesc del\n/physdesc dl [Line to Delete]\n"
    aliases: [pd]
    permission: skysongitems.pd
    permission-message: "You do not have permission to use this command!"
  funcdesc:
    description: "add or set a the Functional description of an item (second paragraph)"
    usage: "/funcdesc add [LORE]\n/funcdesc set [LORE]\n/funcdesc del\n/funcdesc dl [Line to Delete]\n"
    aliases: [ fd ]
    permission: skysongitems.fd
    permission-message: "You do not have permission to use this command!"
  skilldesc:
    description: "add or set a the Skill description of an item (third paragraph)"
    usage: "/skilldesc add [LORE]\n/skilldesc set [LORE]\n/skilldesc del\n/skilldesc dl [Line to Delete]\n"
    aliases: [ sd ]
    permission: skysongitems.sd
    permission-message: "You do not have permission to use this command!"
permissions:
  skysongitems.getlore:
    description: Allows you to perform the getlore command
    default: op
  skysongitems.pd:
    description: Allows you to edit the physical description of an item.
    default: op
  skysongitems.fd:
    description: Allows you to edit the functional description of an item.
    default: op
  skysongitems.sd:
    description: Allows you to edit the skill description of an item.
    default: op
  skysongitems.*:
    description: Wildcard permission
    default: op
    children:
      skysongitems.getlore: true
      skysongitems.pd: true
      skysongitems.fd: true
      skysongitems.sd: true